import type {
  ApprovalQueueItem,
  Client,
  DashboardData,
  DispatchRecord,
  Material,
  NotificationRecord,
  RequestRecord,
  StockSnapshot,
} from "@/types/domain";

export const demoClients: Client[] = [
  {
    id: "client-1",
    branch_id: "demo-branch",
    name: "Apex Path Labs",
    client_code: "CL-1001",
    email: "ops@apexpath.com",
    city: "Indore",
    status: "active",
  },
  {
    id: "client-2",
    branch_id: "demo-branch",
    name: "Medistar Diagnostics",
    client_code: "CL-1002",
    email: "procurement@medistar.in",
    city: "Bhopal",
    status: "active",
  },
  {
    id: "client-3",
    branch_id: "demo-branch",
    name: "Lifeline Biocare",
    client_code: "CL-1003",
    email: "hello@lifelinebio.in",
    city: "Ujjain",
    status: "inactive",
  },
];

export const demoMaterials: Material[] = [
  {
    id: "mat-1",
    sku: "BLOOD-EDTA-02",
    name: "EDTA Blood Collection Tubes",
    category: "Collection",
    unit_of_measure: "box",
    expiry_required: true,
    min_threshold: 120,
    active: true,
  },
  {
    id: "mat-2",
    sku: "URINE-STRIP-10",
    name: "Urine Test Strips",
    category: "Consumables",
    unit_of_measure: "pack",
    expiry_required: true,
    min_threshold: 60,
    active: true,
  },
  {
    id: "mat-3",
    sku: "BIOHAZ-BAG-01",
    name: "Biohazard Disposal Bags",
    category: "Safety",
    unit_of_measure: "bundle",
    expiry_required: false,
    min_threshold: 40,
    active: true,
  },
];

export const demoStock: StockSnapshot[] = [
  {
    id: "stock-1",
    branch_id: "demo-branch",
    material_id: "mat-1",
    material_name: "EDTA Blood Collection Tubes",
    available_quantity: 92,
    reserved_quantity: 18,
    reorder_level: 120,
    nearest_expiry_date: "2026-04-09",
  },
  {
    id: "stock-2",
    branch_id: "demo-branch",
    material_id: "mat-2",
    material_name: "Urine Test Strips",
    available_quantity: 41,
    reserved_quantity: 12,
    reorder_level: 60,
    nearest_expiry_date: "2026-04-15",
  },
  {
    id: "stock-3",
    branch_id: "demo-branch",
    material_id: "mat-3",
    material_name: "Biohazard Disposal Bags",
    available_quantity: 65,
    reserved_quantity: 8,
    reorder_level: 40,
    nearest_expiry_date: null,
  },
];

export const demoRequests: RequestRecord[] = [
  {
    id: "req-1",
    branch_id: "demo-branch",
    client_id: "client-1",
    client_name: "Apex Path Labs",
    request_number: "REQ-2026-0012",
    status: "pending",
    requested_at: "2026-04-02T06:45:00Z",
    needed_by: "2026-04-04",
    total_items: 4,
    total_requested_quantity: 180,
  },
  {
    id: "req-2",
    branch_id: "demo-branch",
    client_id: "client-2",
    client_name: "Medistar Diagnostics",
    request_number: "REQ-2026-0011",
    status: "partially_approved",
    requested_at: "2026-04-01T10:20:00Z",
    needed_by: "2026-04-03",
    total_items: 3,
    total_requested_quantity: 96,
  },
  {
    id: "req-3",
    branch_id: "demo-branch",
    client_id: "client-1",
    client_name: "Apex Path Labs",
    request_number: "REQ-2026-0009",
    status: "approved",
    requested_at: "2026-03-31T08:10:00Z",
    needed_by: "2026-04-02",
    total_items: 2,
    total_requested_quantity: 70,
  },
];

export const demoApprovals: ApprovalQueueItem[] = [
  {
    id: "approval-1",
    request_number: "REQ-2026-0012",
    branch_name: "Indore Central",
    client_name: "Apex Path Labs",
    submitted_by: "Rahul Verma",
    pending_items: 2,
    decision: "pending",
    submitted_at: "2026-04-02T06:45:00Z",
    partial_reason: null,
  },
  {
    id: "approval-2",
    request_number: "REQ-2026-0011",
    branch_name: "Indore Central",
    client_name: "Medistar Diagnostics",
    submitted_by: "Megha Shah",
    pending_items: 1,
    decision: "partially_approved",
    submitted_at: "2026-04-01T10:20:00Z",
    partial_reason: "Insufficient stock for EDTA tubes in current lot.",
  },
];

export const demoDispatches: DispatchRecord[] = [
  {
    id: "disp-1",
    dispatch_number: "DSP-2026-0064",
    request_number: "REQ-2026-0009",
    client_name: "Apex Path Labs",
    branch_name: "Indore Central",
    status: "packed",
    courier_name: "BlueDart",
    tracking_number: "BD11223344",
    dispatched_at: null,
    eta_date: "2026-04-03",
  },
  {
    id: "disp-2",
    dispatch_number: "DSP-2026-0061",
    request_number: "REQ-2026-0008",
    client_name: "Medistar Diagnostics",
    branch_name: "Indore Central",
    status: "dispatched",
    courier_name: "Delhivery",
    tracking_number: "DL99887766",
    dispatched_at: "2026-04-02T04:15:00Z",
    eta_date: "2026-04-03",
  },
];

export const demoNotifications: NotificationRecord[] = [
  {
    id: "note-1",
    title: "Expiry email queued",
    body: "Client email queued for 2 material lots expiring in 7 days.",
    kind: "client_email",
    created_at: "2026-04-02T05:00:00Z",
    read_at: null,
    route: "/dispatch",
  },
  {
    id: "note-2",
    title: "Low stock alert",
    body: "EDTA Blood Collection Tubes crossed the reorder threshold for Indore Central.",
    kind: "internal",
    created_at: "2026-04-02T05:30:00Z",
    read_at: null,
    route: "/materials",
  },
];

export const demoDashboard: DashboardData = {
  metrics: {
    activeClients: 42,
    pendingRequests: 18,
    pendingApprovals: 11,
    dispatchesInFlight: 7,
    expiringSoon: 5,
    lowStockMaterials: 4,
    deliveriesToday: 9,
  },
  requestQueue: demoRequests,
  approvalQueue: demoApprovals,
  lowStock: demoStock.filter((item) => item.available_quantity <= item.reorder_level),
  expiringStock: demoStock.filter((item) => item.nearest_expiry_date),
  dispatches: demoDispatches,
  notifications: demoNotifications,
};
